//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> ca { get; set; }
        public Nullable<int> thu { get; set; }
        public string status { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
